In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 14.0 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [57]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [59]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [4]:
movies_df = pd.read_csv('Source Data/netflix_movies.csv')

In [5]:
movies_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      50 non-null     int64
 1   title         50 non-null     str
 2   genre         50 non-null     str
 3   release_year  50 non-null     int64
dtypes: int64(2), str(2)
memory usage: 1.7 KB

In [7]:
movies_df.head(5)

   movie_id                      title     genre  release_year
0         1            Number Congress    Action          2017
1         2  Employee behavior account  Thriller          2005
2         3         Window around that   Romance          1982
3         4                Wide agency    Comedy          1993
4         5               Rather agree     Drama          2019

In [9]:
movies_df.isnull().sum()

movie_id        0
title           0
genre           0
release_year    0
dtype: int64

In [10]:
movies_df.drop_duplicates(inplace = True)

In [11]:
movies_df.count()

movie_id        50
title           50
genre           50
release_year    50
dtype: int64

In [38]:
movies_df.head(5)

   movie_id                      title     genre  release_year
0         1            Number Congress    Action          2017
1         2  Employee behavior account  Thriller          2005
2         3         Window around that   Romance          1982
3         4                Wide agency    Comedy          1993
4         5               Rather agree     Drama          2019

In [12]:
ratings_df = pd.read_csv('Source Data/netflix_ratings.csv')

In [13]:
ratings_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   rating_id  50 non-null     int64
 1   user_id    50 non-null     int64
 2   movie_id   50 non-null     int64
 3   rating     50 non-null     int64
 4   rated_at   50 non-null     str
dtypes: int64(4), str(1)
memory usage: 2.1 KB

In [14]:
ratings_df.head(5)

   rating_id  user_id  movie_id  rating             rated_at
0          1       13        11       3  2025-03-17 02:43:02
1          2       44        20       5  2024-09-26 15:57:16
2          3       47         6       5  2025-04-29 08:08:54
3          4        5        38       5  2023-10-18 05:01:15
4          5       29        23       3  2024-08-09 10:30:36

In [17]:
ratings_df.isnull().sum()

rating_id    0
user_id      0
movie_id     0
rating       0
rated_at     0
dtype: int64

In [18]:
ratings_df.drop_duplicates(inplace = True)

In [19]:
ratings_df.count()

rating_id    50
user_id      50
movie_id     50
rating       50
rated_at     50
dtype: int64

In [37]:
ratings_df.head(5)

   rating_id  user_id  movie_id  rating             rated_at
0          1       13        11       3  2025-03-17 02:43:02
1          2       44        20       5  2024-09-26 15:57:16
2          3       47         6       5  2025-04-29 08:08:54
3          4        5        38       5  2023-10-18 05:01:15
4          5       29        23       3  2024-08-09 10:30:36

In [20]:
users_df = pd.read_csv('Source Data/netflix_users.csv')

In [21]:
users_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    50 non-null     int64
 1   name       50 non-null     str
 2   email      50 non-null     str
 3   plan_type  50 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.7 KB

In [22]:
users_df.head(5)

   user_id             name                   email plan_type
0        1  Heather Patrick      peggy79@martin.org     Basic
1        2   Michael Bailey       eddie46@yahoo.com  Standard
2        3        Amy Burns   foliver@gallagher.com     Basic
3        4       Cody Estes  allenerika@hotmail.com   Premium
4        5  Richard Schultz      tmerritt@gmail.com     Basic

In [23]:
users_df.isnull().sum()

user_id      0
name         0
email        0
plan_type    0
dtype: int64

In [24]:
users_df.drop_duplicates(inplace = True)

In [26]:
users_df.count()

user_id      50
name         50
email        50
plan_type    50
dtype: int64

In [36]:
users_df.head(5)

   user_id             name                   email plan_type
0        1  Heather Patrick      peggy79@martin.org     Basic
1        2   Michael Bailey       eddie46@yahoo.com  Standard
2        3        Amy Burns   foliver@gallagher.com     Basic
3        4       Cody Estes  allenerika@hotmail.com   Premium
4        5  Richard Schultz      tmerritt@gmail.com     Basic

In [27]:
watch_history_df = pd.read_csv('Source Data/netflix_watch_history.csv')

In [28]:
watch_history_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   history_id  50 non-null     int64
 1   user_id     50 non-null     int64
 2   movie_id    50 non-null     int64
 3   watched_at  50 non-null     str
dtypes: int64(3), str(1)
memory usage: 1.7 KB

In [29]:
watch_history_df.head(5)

   history_id  user_id  movie_id           watched_at
0           1       23        21  2025-04-05 06:20:02
1           2       34        18  2024-03-01 14:16:32
2           3       39        29  2024-12-19 09:14:42
3           4        8        47  2024-03-26 05:58:02
4           5       15         1  2023-12-22 00:20:47

In [30]:
watch_history_df.isnull().sum()

history_id    0
user_id       0
movie_id      0
watched_at    0
dtype: int64

In [31]:
watch_history_df.drop_duplicates(inplace = True)

In [32]:
watch_history_df.count()

history_id    50
user_id       50
movie_id      50
watched_at    50
dtype: int64

In [35]:
watch_history_df.head(5)

   history_id  user_id  movie_id           watched_at
0           1       23        21  2025-04-05 06:20:02
1           2       34        18  2024-03-01 14:16:32
2           3       39        29  2024-12-19 09:14:42
3           4        8        47  2024-03-26 05:58:02
4           5       15         1  2023-12-22 00:20:47

In [45]:
try:
    connection = psycopg2.connect(db_name= 'NETFLIX_DATABASE', user= 'postgres', password = 'postgres', port = '5432')
except:
    print("connection failed")

connection failed

In [46]:
try:
    connection = psycopg2.connect(dbname= 'NETFLIX_DATABASE', user= 'postgres', password = 'postgres', port = '5432')
except:
    print("connection failed")

In [47]:
cursor = connection.cursor()

In [51]:
cursor.execute("""
CREATE TABLE Users (
    user_id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    plan_type VARCHAR(20) CHECK (plan_type IN ('Basic', 'Standard', 'Premium'))
);
"""
)

In [50]:
connection.rollback()

In [52]:
connection.commit()

In [53]:
cursor.execute("""
CREATE TABLE Movies (
    movie_id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    genre VARCHAR(50),
    release_year INTEGER
);
"""
)

In [54]:
cursor.execute("""
CREATE TABLE WatchHistory (
    history_id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES Users(user_id),
    movie_id INTEGER REFERENCES Movies(movie_id),
    watched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""
)

In [55]:
cursor.execute("""
CREATE TABLE Ratings (
    rating_id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES Users(user_id),
    movie_id INTEGER REFERENCES Movies(movie_id),
    rating INTEGER CHECK (rating BETWEEN 1 AND 5),
    rated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""
)

In [56]:
connection.commit()

In [60]:
engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost/NETFLIX_DATABASE')

In [61]:
movies_df.to_sql('movies', con = engine, if_exists = 'append', index = False)

50

In [64]:
ratings_df.to_sql('ratings', con = engine, if_exists = 'append', index = False)

50

In [63]:
users_df.to_sql('users', con = engine, if_exists = 'append', index = False)

50

In [65]:
watch_history_df.to_sql('watchhistory', con = engine, if_exists = 'append', index = False)

50

In [66]:
connection.close()

In [67]:
engine.dispose()